### ISSUE TITLE
Something gets wrong while I am following the tutorial to run the example.

### ISSUE THREAD

**Issue by OwenKZ** [WuDan0399/Integrate-NVDLA-and-TVM#5]
Hello, I get some troubles while I am running the example in the project.

I am running the file "run_LeNet_Relay.py" on Centos7, and I follow all the steps. However, when I run the code sentence `module = nvdla.partition_for_nvdla(module, params=params)` in line 161, errors exist. Here are the errors.

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path-to-tvm/tvm-main/python/tvm/relay/op/contrib/nvdla.py", line 62, in partition_for_nvdla
    return seq(mod)
  File "/path-to-tvm/tvm-main/python/tvm/ir/transform.py", line 127, in __call__
    return _ffi_transform_api.RunPass(self, mod)
  File /path-to-tvm/tvm-main/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
TypeError: Traceback (most recent call last):
  [bt] (8) /path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>::InitVTable()::{lambda(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>*)#5}::_FUN(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>*)+0x13) [0x7f57e52b8a93]
  [bt] (7) /path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::ExprMutator::VisitExpr_(tvm::relay::FunctionNode const*)+0x664) [0x7f57e53f9634]
  [bt] (6) /path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::MixedModeMutator::VisitExpr(tvm::RelayExpr const&)+0x36f) [0x7f57e53fa74f]
  [bt] (5) /path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::MixedModeMutator::VisitLeaf(tvm::RelayExpr const&)+0x45) [0x7f57e53f9be5]
  [bt] (4)/path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::PostOrderRewriter::DispatchVisitExpr(tvm::RelayExpr const&)+0x33) [0x7f57e54000d3]
  [bt] (3) /path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::ExprRewriter::Rewrite(tvm::RelayExpr const&, tvm::RelayExpr const&)+0x79) [0x7f57e519b439]
  [bt] (2)/path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::ExprRewriter::InitVTable()::{lambda(tvm::runtime::ObjectRef const&, tvm::relay::ExprRewriter*, tvm::RelayExpr const&)#6}::_FUN(tvm::runtime::ObjectRef const&, tvm::relay::ExprRewriter*, tvm::RelayExpr const&)+0x14) [0x7f57e51989e4]
  [bt] (1) /path-to-tvm/tvm-main/build/libtvm.so(tvm::relay::annotate_target::AnnotateTargetRewriter::Rewrite_(tvm::relay::CallNode const*, tvm::RelayExpr const&)+0x159f) [0x7f57e520180f]
  [bt] (0) /path-to-tvm/tvm-main/build/libtvm.so(+0x1c6da03) [0x7f57e550fa03]
  File "/path-to-tvm/tvm-main/python/tvm/_ffi/_ctypes/packed_func.py", line 81, in cfun
    rv = local_pyfunc(*pyargs)
TypeError: _func_wrapper() missing 1 required positional argument: 'args'

I have no idea what happens. Hope someone can help me. Thank you!

**Comment by Zzz7Hao** [comment]
Hi, I'm encountering the same issue. Have you found a solution for this?

**Comment by OwenKZ** [comment]
> Hi, I'm encountering the same issue. Have you found a solution for this?

Sorry, it has been a long time ago and I forgot how to fix this bug in detail. I just remembered I used the debug mod of python and found a function that is about this error, then I annotated some lines in that function and finally fixed this bug.

I suggest you use GPT to help you with this error. And I think TVM has been updated and supports an easier way to add customized hardware as your backend.
